Algoritmo "Número par,impar e positivo e negativo."
//Faça um algoritmo que leia um nº inteiro
// e mostre uma mensagem indicando se este número é par ou ímpar,
//e se é positivo ou negativo.
Var
N: real
Inicio
escreva(" Digite um número: ")
leia(N)

se N mod 2 = 0 entao
escreval(" O número é par.")
senao
escreval(" O número é ímpar.")
fimse
se ( N < 0) entao
escreval(" O número é negativo.")
senao
escreval(" O número é positivo.")
fimse


Fimalgoritmo